name: Daily Scraper

on:
  schedule:
    - cron: '0 21 * * *'   # UTC 21:00 = JST 6:00
  workflow_dispatch:

jobs:
  marinemesse_a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests beautifulsoup4
      - name: Run scraper
        run: python marinemesse_a.py


